version: "3.8"

services:
  blogapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waje.blogapi
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=WajeSmart;User Id=sa;Password=Password123@;TrustServerCertificate=True;
      - DOTNET_URLS=http://+:8080
    depends_on:
      - db
    # command: /bin/sh -c "dotnet ef database update && dotnet WajeSmartAssessment.Api.dll"

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: waje.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123@
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
    driver: local
