version: "3.8"

services:
  blog:
    build: "./"
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION_STRING=Server=db;Database=yourdbname;User Id=youruser;Password=yourpassword;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

volumes:
  db-data:
